{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3b44a1d4",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "E:\\abc\\lib\\site-packages\\scipy\\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.3\n",
      "  warnings.warn(f\"A NumPy version >={np_minversion} and <{np_maxversion}\"\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "WARNING:tensorflow:From E:\\abc\\lib\\site-packages\\keras\\src\\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.\n",
      "\n",
      "WARNING:tensorflow:From E:\\abc\\lib\\site-packages\\keras\\src\\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.\n",
      "\n",
      "WARNING:tensorflow:From E:\\abc\\lib\\site-packages\\keras\\src\\layers\\pooling\\max_pooling2d.py:161: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.\n",
      "\n",
      "Epoch 1/10\n",
      "WARNING:tensorflow:From E:\\abc\\lib\\site-packages\\keras\\src\\utils\\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.\n",
      "\n",
      "2/8 [======>.......................] - ETA: 2:17 - loss: 1.7886"
     ]
    },
    {
     "ename": "AbortedError",
     "evalue": "Graph execution error:\n\nDetected at node sequential/conv2d_3/Relu defined at (most recent call last):\n  File \"E:\\abc\\lib\\runpy.py\", line 197, in _run_module_as_main\n\n  File \"E:\\abc\\lib\\runpy.py\", line 87, in _run_code\n\n  File \"E:\\abc\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n\n  File \"E:\\abc\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n\n  File \"E:\\abc\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n\n  File \"E:\\abc\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n\n  File \"E:\\abc\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n\n  File \"E:\\abc\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n\n  File \"E:\\abc\\lib\\asyncio\\events.py\", line 80, in _run\n\n  File \"E:\\abc\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n\n  File \"E:\\abc\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n\n  File \"E:\\abc\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n\n  File \"E:\\abc\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n\n  File \"E:\\abc\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 390, in do_execute\n\n  File \"E:\\abc\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n\n  File \"E:\\abc\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2914, in run_cell\n\n  File \"E:\\abc\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2960, in _run_cell\n\n  File \"E:\\abc\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n\n  File \"E:\\abc\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3185, in run_cell_async\n\n  File \"E:\\abc\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3377, in run_ast_nodes\n\n  File \"E:\\abc\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3457, in run_code\n\n  File \"C:\\Users\\LENOVO L460\\AppData\\Local\\Temp\\ipykernel_3996\\2089139049.py\", line 93, in <module>\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 65, in error_handler\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 1807, in fit\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 1401, in train_function\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 1384, in step_function\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 1373, in run_step\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 1150, in train_step\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 65, in error_handler\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 590, in __call__\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 65, in error_handler\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\engine\\base_layer.py\", line 1149, in __call__\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 96, in error_handler\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\engine\\sequential.py\", line 398, in call\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\engine\\functional.py\", line 515, in call\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\engine\\functional.py\", line 672, in _run_internal_graph\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 65, in error_handler\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\engine\\base_layer.py\", line 1149, in __call__\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 96, in error_handler\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\layers\\convolutional\\base_conv.py\", line 321, in call\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\activations.py\", line 306, in relu\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\backend.py\", line 5395, in relu\n\nOperation received an exception:Status: 1, message: could not create a memory object, in file tensorflow/core/kernels/mkl/mkl_conv_ops.cc:1093\n\t [[{{node sequential/conv2d_3/Relu}}]] [Op:__inference_train_function_1714]",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mAbortedError\u001b[0m                              Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp\\ipykernel_3996\\2089139049.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m     91\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     92\u001b[0m \u001b[1;31m# Train the height model\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 93\u001b[1;33m \u001b[0mmodel_height\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX_train\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my_height_train\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mepochs\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m10\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mbatch_size\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;36m32\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     94\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     95\u001b[0m \u001b[1;31m# Define the CNN model architecture for weight prediction\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mE:\\abc\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\u001b[0m in \u001b[0;36merror_handler\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     68\u001b[0m             \u001b[1;31m# To get the full stack trace, call:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     69\u001b[0m             \u001b[1;31m# `tf.debugging.disable_traceback_filtering()`\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 70\u001b[1;33m             \u001b[1;32mraise\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mwith_traceback\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mfiltered_tb\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;32mfrom\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     71\u001b[0m         \u001b[1;32mfinally\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     72\u001b[0m             \u001b[1;32mdel\u001b[0m \u001b[0mfiltered_tb\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mE:\\abc\\lib\\site-packages\\tensorflow\\python\\eager\\execute.py\u001b[0m in \u001b[0;36mquick_execute\u001b[1;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[0;32m     51\u001b[0m   \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     52\u001b[0m     \u001b[0mctx\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mensure_initialized\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 53\u001b[1;33m     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n\u001b[0m\u001b[0;32m     54\u001b[0m                                         inputs, attrs, num_outputs)\n\u001b[0;32m     55\u001b[0m   \u001b[1;32mexcept\u001b[0m \u001b[0mcore\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_NotOkStatusException\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mAbortedError\u001b[0m: Graph execution error:\n\nDetected at node sequential/conv2d_3/Relu defined at (most recent call last):\n  File \"E:\\abc\\lib\\runpy.py\", line 197, in _run_module_as_main\n\n  File \"E:\\abc\\lib\\runpy.py\", line 87, in _run_code\n\n  File \"E:\\abc\\lib\\site-packages\\ipykernel_launcher.py\", line 17, in <module>\n\n  File \"E:\\abc\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n\n  File \"E:\\abc\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 712, in start\n\n  File \"E:\\abc\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n\n  File \"E:\\abc\\lib\\asyncio\\base_events.py\", line 601, in run_forever\n\n  File \"E:\\abc\\lib\\asyncio\\base_events.py\", line 1905, in _run_once\n\n  File \"E:\\abc\\lib\\asyncio\\events.py\", line 80, in _run\n\n  File \"E:\\abc\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 510, in dispatch_queue\n\n  File \"E:\\abc\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 499, in process_one\n\n  File \"E:\\abc\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 406, in dispatch_shell\n\n  File \"E:\\abc\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 730, in execute_request\n\n  File \"E:\\abc\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 390, in do_execute\n\n  File \"E:\\abc\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 528, in run_cell\n\n  File \"E:\\abc\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2914, in run_cell\n\n  File \"E:\\abc\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2960, in _run_cell\n\n  File \"E:\\abc\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 78, in _pseudo_sync_runner\n\n  File \"E:\\abc\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3185, in run_cell_async\n\n  File \"E:\\abc\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3377, in run_ast_nodes\n\n  File \"E:\\abc\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3457, in run_code\n\n  File \"C:\\Users\\LENOVO L460\\AppData\\Local\\Temp\\ipykernel_3996\\2089139049.py\", line 93, in <module>\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 65, in error_handler\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 1807, in fit\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 1401, in train_function\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 1384, in step_function\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 1373, in run_step\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 1150, in train_step\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 65, in error_handler\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\engine\\training.py\", line 590, in __call__\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 65, in error_handler\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\engine\\base_layer.py\", line 1149, in __call__\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 96, in error_handler\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\engine\\sequential.py\", line 398, in call\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\engine\\functional.py\", line 515, in call\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\engine\\functional.py\", line 672, in _run_internal_graph\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 65, in error_handler\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\engine\\base_layer.py\", line 1149, in __call__\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 96, in error_handler\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\layers\\convolutional\\base_conv.py\", line 321, in call\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\activations.py\", line 306, in relu\n\n  File \"E:\\abc\\lib\\site-packages\\keras\\src\\backend.py\", line 5395, in relu\n\nOperation received an exception:Status: 1, message: could not create a memory object, in file tensorflow/core/kernels/mkl/mkl_conv_ops.cc:1093\n\t [[{{node sequential/conv2d_3/Relu}}]] [Op:__inference_train_function_1714]"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import tensorflow as tf\n",
    "import logging\n",
    "import time\n",
    "import tkinter as tk\n",
    "from tkinter import filedialog\n",
    "from PIL import ImageTk, Image\n",
    "import cv2\n",
    "import pandas as pd\n",
    "from pathlib import Path\n",
    "\n",
    "# Set random seeds for reproducibility\n",
    "np.random.seed(42)\n",
    "tf.random.set_seed(42)\n",
    "\n",
    "# Configure logging\n",
    "logging.basicConfig(filename='bmi.log', level=logging.INFO, format='%(asctime)s:%(levelname)s:%(message)s')\n",
    "\n",
    "# Load CSV data\n",
    "df = pd.read_csv(\"bmi data set.csv\")\n",
    "\n",
    "# Define function to get index of the first digit in a string\n",
    "def get_index_of_digit(string):\n",
    "    for i, char in enumerate(string):\n",
    "        if char.isdigit():\n",
    "            return i\n",
    "    return -1\n",
    "\n",
    "# Function to preprocess and encode full-body images\n",
    "def encode_full_body_image(image_path):\n",
    "    # Load and preprocess the image\n",
    "    image = tf.keras.preprocessing.image.load_img(image_path, target_size=(224, 224))\n",
    "    image = tf.keras.preprocessing.image.img_to_array(image)\n",
    "    image = image / 255.0  # Normalize pixel values\n",
    "    return image\n",
    "\n",
    "# Load full-body image paths and corresponding IDs\n",
    "data_folder = \"sample_faces\"\n",
    "all_files = list(Path(data_folder).glob(\"*.[jJpP][pPnN][gG]\"))\n",
    "id_dir = [(Path(images).stem[:get_index_of_digit(Path(images).stem)], images) for images in all_files]\n",
    "\n",
    "# Create DataFrame from full-body image paths and corresponding IDs\n",
    "image_df = pd.DataFrame(id_dir, columns=['UID', 'path'])\n",
    "\n",
    "# Merge full-body image DataFrame with CSV data\n",
    "data_df = image_df.merge(df, on='UID')\n",
    "\n",
    "# Prepare data for training\n",
    "X_train = []\n",
    "y_height_train = []\n",
    "y_weight_train = []\n",
    "\n",
    "# Iterate through each image file\n",
    "for image_file in data_df['path']:\n",
    "    uid = Path(image_file).stem.split(\"_\")[0]  # Extract UID from filename\n",
    "    \n",
    "    # Encode the full-body image\n",
    "    encoded_image = encode_full_body_image(image_file)\n",
    "    X_train.append(encoded_image)\n",
    "    \n",
    "    # Extract corresponding height and weight from CSV data\n",
    "    height = data_df.loc[data_df['path'] == image_file, 'height'].values[0]\n",
    "    weight = data_df.loc[data_df['path'] == image_file, 'weight'].values[0]\n",
    "    y_height_train.append(height)\n",
    "    y_weight_train.append(weight)\n",
    "\n",
    "# Convert lists to arrays\n",
    "X_train = np.array(X_train)\n",
    "y_height_train = np.array(y_height_train)\n",
    "y_weight_train = np.array(y_weight_train)\n",
    "\n",
    "# Define the CNN model architecture for height prediction\n",
    "model_height = tf.keras.Sequential([\n",
    "    tf.keras.layers.Conv2D(64, (3, 3), activation='relu', input_shape=(224, 224, 3)),\n",
    "    tf.keras.layers.MaxPooling2D((2, 2)),\n",
    "    tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),\n",
    "    tf.keras.layers.MaxPooling2D((2, 2)),\n",
    "    tf.keras.layers.Conv2D(256, (3, 3), activation='relu'),\n",
    "    tf.keras.layers.MaxPooling2D((2, 2)),\n",
    "    tf.keras.layers.Conv2D(512, (3, 3), activation='relu'),\n",
    "    tf.keras.layers.MaxPooling2D((2, 2)),\n",
    "    tf.keras.layers.Flatten(),\n",
    "    tf.keras.layers.Dense(256, activation='relu'),\n",
    "    tf.keras.layers.Dropout(0.5),\n",
    "    tf.keras.layers.Dense(1)  # Output layer for height prediction\n",
    "])\n",
    "\n",
    "# Compile the height model\n",
    "optimizer_height = tf.keras.optimizers.Adam(learning_rate=1e-4)  # Adjust learning rate\n",
    "model_height.compile(optimizer=optimizer_height, loss='mean_squared_error')\n",
    "\n",
    "# Train the height model\n",
    "model_height.fit(X_train, y_height_train, epochs=10, batch_size=32)\n",
    "\n",
    "# Define the CNN model architecture for weight prediction\n",
    "model_weight = tf.keras.Sequential([\n",
    "    tf.keras.layers.Conv2D(64, (3, 3), activation='relu', input_shape=(224, 224, 3)),\n",
    "    tf.keras.layers.MaxPooling2D((2, 2)),\n",
    "    tf.keras.layers.Conv2D(128, (3, 3), activation='relu'),\n",
    "    tf.keras.layers.MaxPooling2D((2, 2)),\n",
    "    tf.keras.layers.Conv2D(256, (3, 3), activation='relu'),\n",
    "    tf.keras.layers.MaxPooling2D((2, 2)),\n",
    "    tf.keras.layers.Conv2D(512, (3, 3), activation='relu'),\n",
    "    tf.keras.layers.MaxPooling2D((2, 2)),\n",
    "    tf.keras.layers.Flatten(),\n",
    "    tf.keras.layers.Dense(256, activation='relu'),\n",
    "    tf.keras.layers.Dropout(0.5),\n",
    "    tf.keras.layers.Dense(1)  # Output layer for weight prediction\n",
    "])\n",
    "\n",
    "# Compile the weight model\n",
    "optimizer_weight = tf.keras.optimizers.Adam(learning_rate=1e-4)  # Adjust learning rate\n",
    "model_weight.compile(optimizer=optimizer_weight, loss='mean_squared_error')\n",
    "\n",
    "# Train the weight model \n",
    "model_weight.fit(X_train, y_weight_train, epochs=10, batch_size=32)\n",
    "\n",
    "# Function to predict height and weight for a given image\n",
    "def predict_height_weight(input_img, height_model, weight_model):\n",
    "    logging.info(\"Predicting height and weight for image %s\", input_img)\n",
    "    start_time = time.time()\n",
    "    test_array = np.expand_dims(np.array(encode_full_body_image(input_img)), axis=0)\n",
    "    height = height_model.predict(test_array)[0][0]*3.28084\n",
    "    weight = weight_model.predict(test_array)[0][0]\n",
    "    bmi = weight / ((height / 3.28084) ** 2)\n",
    "    end_time = time.time()\n",
    "    runtime = end_time - start_time\n",
    "    logging.info(\"Predicted height: %f, weight: %f, BMI: %f, runtime: %s\", height, weight, bmi, runtime)\n",
    "    return {'height': height, 'weight': weight, 'bmi': bmi, 'runtime': runtime}\n",
    "\n",
    "# Create GUI for image input and prediction display\n",
    "root = tk.Tk()\n",
    "root.title(\"BMI Prediction\")\n",
    "\n",
    "\n",
    "def browse_image():\n",
    "    file_path = filedialog.askopenfilename()\n",
    "    img = Image.open(file_path)\n",
    "    img = img.resize((300, 500), Image.ANTIALIAS)\n",
    "    img = ImageTk.PhotoImage(img)\n",
    "    panel = tk.Label(root, image=img)\n",
    "    panel.image = img\n",
    "    panel.grid(row=0, column=0, columnspan=2)\n",
    "    predict_button[\"state\"] = tk.NORMAL\n",
    "    global image_path\n",
    "    image_path = file_path\n",
    "\n",
    "def predict_bmi():\n",
    "    prediction = predict_height_weight(image_path, model_height, model_weight)\n",
    "    prediction_label.config(text=f\"Predicted Height: {prediction['height']:.2f} feet\\nPredicted Weight: {prediction['weight']:.2f}\\nPredicted BMI: {prediction['bmi']:.2f}\")\n",
    "\n",
    "browse_button = tk.Button(root, text=\"Browse Image\", command=browse_image)\n",
    "browse_button.grid(row=1, column=0)\n",
    "\n",
    "predict_button = tk.Button(root, text=\"Predict BMI\", command=predict_bmi, state=tk.DISABLED)\n",
    "predict_button.grid(row=1, column=1)\n",
    "\n",
    "prediction_label = tk.Label(root, text=\"\")\n",
    "prediction_label.grid(row=2, column=0, columnspan=2)\n",
    "\n",
    "root.mainloop()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f994745a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
